name: quotes_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flexify: ^2.1.1
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.1.0
  share_extend: ^2.0.0
  image_gallery_saver: ^2.0.3
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/views/SplashScreen/assets/

  fonts:
    - family: billingLotre
      fonts:
        - asset: assets/fonts/bl.ttf
    - family: champagneLimousines
      fonts:
        - asset: assets/fonts/cl.ttf
    - family: chiro
      fonts:
        - asset: assets/fonts/cr.ttf
    - family: designer
      fonts:
        - asset: assets/fonts/ds.otf
    - family: lemonMilk
      fonts:
        - asset: assets/fonts/lm.otf
    - family: miroles
      fonts:
        - asset: assets/fonts/mi.ttf
    - family: newYork
      fonts:
        - asset: assets/fonts/ny.otf
